{% set name = "vp4jl" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/vp4jl-{{ version }}.tar.gz
  sha256: 7542e05d5bb4b076ce6a47172f73bb60d051e773d83a1fe2c1351ae2e4d2affe

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - hatchling >=1.5.0
    - jupyterlab >=4.0.0b0,<5
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - pip
  run:
    - python >=3.8
    - jupyter_server >=2.0.1,<3

test:
  imports:
    - vp4jl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Max-ChenFei/VisualProgramming4JupyterLab
  summary: The JupyterLab extension providing node based visual programming environment
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
